services:

  server:
    restart: always
    build: .
    command: >
      sh -c "cd /app/src/
      && mkdir -p media
      && poetry run python manage.py migrate --noinput
      && poetry run python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - "DEBUG=1"
    env_file:
      - ".env"

  redis:
    image: redis:7-alpine
    restart: always 
    ports:
      - "6379:6379"
